<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DAPEO3T" ignored="0" name="RetryMultipleFailedTestCases" tests="9" failures="2" timestamp="14 Jul 2018 07:48:24 GMT" time="0.187" errors="0">
  <testcase name="Test1" time="0.02" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.007" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="mytests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test1(MyTests.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.005" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="mytests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test2(MyTests.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="mytests.MyTests"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
